ip: 0.0.0.0
port: 8000
timeout: 60
default: templates/localhost

virtualhosts:
  - name: akali
    path: templates/akali
    default: 404.html

  - name: akali.local
    path: templates/akalilocal
    default: 404.html